
language : python
sudo : false
cache : false
python :
    - "3.4"
    - "3.5"

install :
    - pip install .
    - pip install -r requirements.txt
    - python setup.py install

matrix :
    include :
        - os : linux
          dist : precise
          sudo : required
          python : 3.4
        - os : linux
          dist : trusty
          sudo : required
          python : 3.4
        - os : linux
          dist : precise
          sudo : required
          python : 3.5
        - os : linux
          dist : trusty
          sudo : required
          python : 3.5

script : py.test
